package no.simula.corona.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import no.simula.corona.data.greendao.Measurement;
import no.simula.corona.data.greendao.BluetoothContact;

import no.simula.corona.data.greendao.MeasurementDao;
import no.simula.corona.data.greendao.BluetoothContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig measurementDaoConfig;
    private final DaoConfig bluetoothContactDaoConfig;

    private final MeasurementDao measurementDao;
    private final BluetoothContactDao bluetoothContactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        measurementDaoConfig = daoConfigMap.get(MeasurementDao.class).clone();
        measurementDaoConfig.initIdentityScope(type);

        bluetoothContactDaoConfig = daoConfigMap.get(BluetoothContactDao.class).clone();
        bluetoothContactDaoConfig.initIdentityScope(type);

        measurementDao = new MeasurementDao(measurementDaoConfig, this);
        bluetoothContactDao = new BluetoothContactDao(bluetoothContactDaoConfig, this);

        registerDao(Measurement.class, measurementDao);
        registerDao(BluetoothContact.class, bluetoothContactDao);
    }
    
    public void clear() {
        measurementDaoConfig.clearIdentityScope();
        bluetoothContactDaoConfig.clearIdentityScope();
    }

    public MeasurementDao getMeasurementDao() {
        return measurementDao;
    }

    public BluetoothContactDao getBluetoothContactDao() {
        return bluetoothContactDao;
    }

}
